/**
 * IPC channel names are kept in a dependency-free module so the Electron
 * sandboxed preload can bundle them without pulling validation libraries into
 * its restricted runtime.
 */
export const IPC_CHANNELS = {
  bootstrap: "maestro:bootstrap",
  projectCreate: "maestro:project:create",
  projectList: "maestro:project:list",
  projectSelect: "maestro:project:select",
  projectUpdate: "maestro:project:update",
  projectDelete: "maestro:project:delete",
  projectAddRoot: "maestro:project:add-root",
  projectRemoveRoot: "maestro:project:remove-root",
  selectDirectory: "maestro:dialog:select-directory",
  contextSelectFiles: "maestro:context:select-files",
  contextSelectFolder: "maestro:context:select-folder",
  contextStageDrop: "maestro:context:stage-drop",
  contextStageClipboard: "maestro:context:stage-clipboard",
  contextStageRecording: "maestro:context:stage-recording",
  contextSearchWorkspace: "maestro:context:search-workspace",
  contextPrepareWorkspace: "maestro:context:prepare-workspace",
  contextList: "maestro:context:list",
  contextRemove: "maestro:context:remove",
  localModelState: "maestro:local-model:state",
  localModelDownload: "maestro:local-model:download",
  localModelCancel: "maestro:local-model:cancel",
  localModelRemove: "maestro:local-model:remove",
  conversationCreate: "maestro:conversation:create",
  conversationList: "maestro:conversation:list",
  conversationGet: "maestro:conversation:get",
  conversationUpdate: "maestro:conversation:update",
  conversationDelete: "maestro:conversation:delete",
  messageSend: "maestro:message:send",
  runGet: "maestro:run:get",
  runEvents: "maestro:run:events",
  runApprove: "maestro:run:approve",
  runRevise: "maestro:run:revise",
  runCancel: "maestro:run:cancel",
  providerRefresh: "maestro:provider:refresh",
  providerConfigure: "maestro:provider:configure",
  providerConnectionCreate: "maestro:provider-connection:create",
  providerConnectionUpdate: "maestro:provider-connection:update",
  providerConnectionReorder: "maestro:provider-connection:reorder",
  providerConnectionDelete: "maestro:provider-connection:delete",
  providerConnectionLogin: "maestro:provider-connection:login",
  settingsUpdate: "maestro:settings:update",
  vaultUnlock: "maestro:vault:unlock",
  vaultLock: "maestro:vault:lock",
  updateCheck: "maestro:update:check",
  updateDownload: "maestro:update:download",
  updateInstall: "maestro:update:install",
  terminalCreate: "maestro:terminal:create",
  terminalWrite: "maestro:terminal:write",
  terminalResize: "maestro:terminal:resize",
  terminalKill: "maestro:terminal:kill",
  eventRun: "maestro:event:run",
  eventTerminal: "maestro:event:terminal",
  eventUpdate: "maestro:event:update",
  eventContext: "maestro:event:context",
  eventLocalModel: "maestro:event:local-model",
  windowMinimize: "maestro:window:minimize",
  windowMaximize: "maestro:window:maximize",
  windowClose: "maestro:window:close",
} as const;
