/**
 * IPC channel names are kept in a dependency-free module so the Electron
 * sandboxed preload can bundle them without pulling validation libraries into
 * its restricted runtime.
 */
export const IPC_CHANNELS = {
  bootstrap: "maestro:bootstrap",
  projectCreate: "maestro:project:create",
  projectList: "maestro:project:list",
  projectSelect: "maestro:project:select",
  projectAddRoot: "maestro:project:add-root",
  selectDirectory: "maestro:dialog:select-directory",
  selectAttachments: "maestro:dialog:select-attachments",
  conversationCreate: "maestro:conversation:create",
  conversationList: "maestro:conversation:list",
  conversationGet: "maestro:conversation:get",
  messageSend: "maestro:message:send",
  runGet: "maestro:run:get",
  runEvents: "maestro:run:events",
  runApprove: "maestro:run:approve",
  runRevise: "maestro:run:revise",
  runCancel: "maestro:run:cancel",
  providerRefresh: "maestro:provider:refresh",
  providerConfigure: "maestro:provider:configure",
  providerConnectionCreate: "maestro:provider-connection:create",
  providerConnectionUpdate: "maestro:provider-connection:update",
  providerConnectionDelete: "maestro:provider-connection:delete",
  providerConnectionLogin: "maestro:provider-connection:login",
  settingsUpdate: "maestro:settings:update",
  vaultUnlock: "maestro:vault:unlock",
  vaultLock: "maestro:vault:lock",
  updateCheck: "maestro:update:check",
  updateDownload: "maestro:update:download",
  updateInstall: "maestro:update:install",
  terminalCreate: "maestro:terminal:create",
  terminalWrite: "maestro:terminal:write",
  terminalResize: "maestro:terminal:resize",
  terminalKill: "maestro:terminal:kill",
  eventRun: "maestro:event:run",
  eventTerminal: "maestro:event:terminal",
  eventUpdate: "maestro:event:update",
  windowMinimize: "maestro:window:minimize",
  windowMaximize: "maestro:window:maximize",
  windowClose: "maestro:window:close",
} as const;
